# runs important stuff before doing something cool or stupid

repos:
  # --- Python formatting ---
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: black (backend)
        files: ^backend/
  
  # --- import sort ---
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (backend)
        files: ^backend/

  # --- JavaScript / React formatting ---
  - repo: local
    hooks:
      - id: prettier
        name: prettier (frontend-ministry)
        entry: npx prettier --write
        language: node
        types_or: [javascript, jsx, ts, tsx, json, css, html]
        files: ^frontend-ministry/
