#!/usr/bin/env bash

# runs python scripts at ./scripts
# provide just the file body
# example:
# ./runscript downscale_images

source ./activate-venv

if [ "$1" == "serve" ]; then
    python ./py/serve.py
else
    python ./py/runscript.py $1
fi
